### ISSUE TITLE
change function for map does not appear to work correctly

### ISSUE THREAD

**Issue by jaycunningham-8451** [dbrattli/Expression#105]
**Describe the bug**
This may not be a bug, but I can't find documentation for the `change` function / method as it applies to `map`s. It certainly does not appear to operate in a way that I would expect.

Calling `change` on an existing, nonempty map appears to operate as if it were called on an empty map.

**To Reproduce**

This results in a `Nothing_` error, when I would expect it to return the `map` unchanged:

```python
from expression.collections import Map

xs = Map.of(**dict(a=10, b=20))
xs.change("a", lambda x: x)
```

This results in `map [("a", 1)]` when I would expect `map [("a", 1); ("b", 20)]`:

```python
xs.change("a", lambda _: Some(1))
```

**Expected behavior**
As indicated above, I would expect that the first block would return the map unchanged, and that the second would only modify the item with the key `"a"`.

**Additional context**

 - OS MacOS 13
 - Expression version 4.2.2
 - Python version 3.11.1

**Comment by matiboy** [comment]
I'm facing the same issue; a bit more specifically, the map can only change the last item added:

```python
def test_expression_issue():
    m = Map.empty()
    m = m.add("a", 1)
    m = m.add("d", 42)
    print(m) # map [("a", 1); ("d", 42)]
    print(m.get("a")) # 1
    print(m.get("d")) # 42, so both keys are in the map
    m = m.change("d", lambda x: x) #<- works cause d was added last
    print(m) # map [("a", 1); ("d", 42)] Both keys still there
    m = m.change("a", lambda x: x) # fails; if this was the first call to change, it would also fail
    assert m
```

**Comment by matiboy** [comment]
I noticed that the code in `maptree.py` lines 315 and 328 uses `rebalance` but does not _return it_ which seems wrong since that would mean it has side effects (right?)

Adding `return rebalance(...` makes the tests I wrote pass, and all other tests still pass too. I'll create a PR but hopefully the authors/maintainers can have a close look because I know very little about MapTrees and generally functional programming.
