### ISSUE TITLE
seq.map does not type check correctly

### ISSUE THREAD

**Issue by evanlouie** [dbrattli/Expression#167]
**Describe the bug**

The functional `pipe` examples where `seq.map` is the first function in the pipe causes a type error.

**To Reproduce**

<img width="686" alt="Screenshot 2023-07-26 at 17 58 18" src="https://github.com/cognitedata/Expression/assets/2081587/a069784b-4085-4860-a16a-c68a37862d9e">

**Expected behavior**

pyright type checks correctly

**Code or Screenshots**

This causes type error:

```python
from expression.collections import seq, Seq

xs = Seq.of(9, 10, 11)
ys = xs.pipe(
    seq.map(lambda x: x * 10),
    seq.filter(lambda x: x > 100),
    seq.fold(lambda s, x: s + x, 0)
)
```

This passes:

```python
from expression.collections import seq, Seq

xs = Seq.of(9, 10, 11)
ys = xs.pipe(
    seq.filter(lambda x: x > 100),
    seq.map(lambda x: x * 10),
    seq.fold(lambda s, x: s + x, 0)
)
```

**Additional context**

 - MacOS
 - Expression version 4.2.4
 - Tested on Python 3.11.4 and 3.10.12

**Comment by dbrattli** [comment]
Hi Pyright is unfortunately not good at inferring the types of lambda functions. The problem here is not `seq.map` nor the pipe method. To fix this (until pyright can infer the types better) you need to assign the lambdas to variables and give them types e.g:
```py
mapper: Callable[[int], int] = lambda x: x * 10
predicate: Callable[[int], bool] = lambda x: x > 100
folder: Callable[[int, int], int] = lambda s, x: s + x

ys = xs.pipe(
    seq.map(mapper),
    seq.filter(predicate),
    seq.fold(folder, 0),
)
```
I'll update the examples
