### ISSUE TITLE
Why was it changed to `python>=3.11`?

### ISSUE THREAD

**Issue by phi-friday** [dbrattli/Expression#216]
**Is your feature request related to a problem? Please describe.**
https://github.com/dbrattli/Expression/issues/107#issuecomment-1893145496

I noticed that it changed to support `python>=3.11` starting with `v5`.
The `dataclass_transform` is also in `typing_extensions`, which is now added as a dependency,
is there any other reason why it was imported from `typing` and changed to `python>=3.11`?
(like `match ~ case` syntax)

**Describe alternatives you've considered**

**Additional context**

**Comment by dbrattli** [comment]
Fixed by #217. Thanks for the PR.
