### ISSUE TITLE
Covariance/Contravariance of Result

### ISSUE THREAD

**Issue by ShravanSunder** [dbrattli/Expression#221]
I'm having an issue using in a covariant manner
```
  @abstractmethod
  async def start(self, event: WorkflowStartEvent[t.Any]) -> Result[t.Tuple[WorkflowEventBase, ...], WorkflowErrorEvent]:
    """Abstract method to be implemented by subclasses for workflow initialization."""
    pass

class GenerateAgentToolIntrospectionEvent(WorkflowEventBase):
  pass

class CreateAgentToolWorkflow(Workflow[GenerateAgentToolWorkflowContext]):
  async def start(
    self,
    event: WorkflowStartEvent[PythonModuleToolConfiguration],
  ) -> Result[t.Tuple[GenerateAgentToolIntrospectionEvent, ...], WorkflowErrorEvent]:
    raise NotImplementedError()
```

In the example below i'd like to inherit start and return a more specific type of WorkflowBaseEvent

I think because Result:`_TSource = TypeVar("_TSource")` doesn't allow covariance.  Is there any to handle this @dbrattli?  if do change as a test `_TSource = TypeVar("_TSource", covariant=True)` it does work, however maybe such a chagne in the library would have other impatc

**Comment by dbrattli** [comment]
This is related to #171 and #190

**Comment by dbrattli** [comment]
Should be fixed. Please re-open if still an issue
